cargo-features = ["edition2021"]

[package]
name = "yolo-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "*"
num-bigint = "*"
anyhow = "*"

